#default
io:
  honeymon:
    name: 김지헌
    age: 30
    email: ihoneymon@gmail.com
    homesite: http://honeymon.io

---

spring:
  profiles: develop
io:
  honeymon:
    name: Honeymon
    age: 26
    homesite: http://ihoney.pe.kr
    #https://ihoney.pe.kr/4 2006

---

spring:
  profiles: beta
io:
  honeymon:
    name: Honeymon
    age: 29
    homesite: http://java.ihoney.pe.kr
    # https://java.ihoney.pe.kr/1 2009

---

spring:
  profiles: prod
io:
  honeymon:
      name: 김지헌
      age: 39
      homesite: http://honeymon.io
      # http://honeymon.io/notice/2018/02/26/remodeling-honeymon-io.html 2018