info:
  app:
    encoding: UTF-8
    name: bootiful-api
spring.boot.admin.client.url: http://localhost:8080
server:
  port: 9090
management.endpoints.web.exposure.include: "*"
spring:
  profiles:
    include:
      - core